const images = {
  nav: require('../../../../../assets/new_images/nav.png'),
  benefit: require('../../../../../assets/new_images/benefit.png'),
  settings: require('../../../../../assets/new_images/settings.png'),
  smile_Emoji: require('../../../../../assets/new_images/smile_Emoji.png'),
  chat: require('../../../../../assets/new_images/chat.png'),
  journal: require('../../../../../assets/new_images/journal.png'),
  location: require('../../../../../assets/new_images/location.png'),
  chevron: require('../../../../../assets/new_images/chevron.png'),
  lock: require('../../../../../assets/new_images/lock.png'),
  account: require('../../../../../assets/new_images/account.png'),
  logoutButton: require('../../../../../assets/new_images/logoutButton.png'),
  back: require('../../../../../assets/new_images/back.png'),
  goals: require('../../../../../assets/new_images/goals.png'),
  logEmoji: require('../../../../../assets/new_images/logEmoji.png'),
  c4Baground: require('../../../../../assets/new_images/c4Baground.png'),

  journalButton: require('../../../../../assets/new_images/journalButton.png'),
  notDone: require('../../../../../assets/new_images/notDone.png'),

  greatEmoji: require('../../../../../assets/new_images/checkIn/greatEmoji.png'),
  goodEmoji: require('../../../../../assets/new_images/checkIn/goodEmoji.png'),
  okEmoji: require('../../../../../assets/new_images/checkIn/okEmoji.png'),
  notGoodEmoji: require('../../../../../assets/new_images/checkIn/notGoodEmoji.png'),
  terribleEmoji: require('../../../../../assets/new_images/checkIn/terribleEmoji.png'),
  skip: require('../../../../../assets/new_images/checkIn/skip.png'),
  custom: require('../../../../../assets/new_images/checkIn/custom.png'),
  completeCheckIn: require('../../../../../assets/new_images/checkIn/completeCheckIn.png'),
  Tip: require('../../../../../assets/new_images/checkIn/Tip.png'),
  close: require('../../../../../assets/new_images/checkIn/close.png'),
  menu: require('../../../../../assets/new_images/checkIn/menuVertical.png'),
  plus: require('../../../../../assets/new_images/checkIn/plus.png'),
}
export default images
