const tagTypes = [
  'User',
  'UNAUTHORIZED',
  'Client',
  'Practitioner',
  'Practice',
  'Todo',
  'Message',
  'Category',
  'Result',
  'Questionnaire',
  'QuestionnaireResult',
  'AssignedResource',
  'Content',
  'Notification',
  'Journey',
  'AssignedJourney',
  'ClientMilestoneStop',
  'JourneySuggestion',
  'ClientInsightsPreset',
  'LoggedEvent',
  'CheckIn',
  'JournalEntry',
  'Goal',
  'ClientContent',
  'Worksheet',
  'ClientWorksheet',
  'CaseNote',
  'Appointment',
  'RecurringAppointment',
] as const
export default tagTypes
export type ApiTags = (typeof tagTypes)[number]
